CREATE TABLE PRODUCTO (
    ID_PRODUCTO      NUMBER(10)        PRIMARY KEY,
    CODIGO           VARCHAR2(20)       NOT NULL,
    NOMBRE           VARCHAR2(120)      NOT NULL,
    MARCA            VARCHAR2(60)       NOT NULL,
    MODELO           VARCHAR2(60)       NOT NULL,
    PRECIO           NUMBER(10,2)       NOT NULL,
    STOCK            NUMBER(10)         NOT NULL,
    ESTADO            CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_CREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_MODIF      TIMESTAMP
);
ALTER TABLE PRODUCTO
ADD CONSTRAINT UK_PRODUCTO_CODIGO
UNIQUE (CODIGO);

CREATE INDEX IDX_PRODUCTO_MARCA_MODELO
ON PRODUCTO (MARCA, MODELO);

CREATE SEQUENCE SEQ_PRODUCTO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE PACKAGE PKG_PRODUCTO AS

    PROCEDURE SP_CREAR_PRODUCTO (
        P_CODIGO   IN PRODUCTO.CODIGO%TYPE,
        P_NOMBRE   IN PRODUCTO.NOMBRE%TYPE,
        P_MARCA    IN PRODUCTO.MARCA%TYPE,
        P_MODELO   IN PRODUCTO.MODELO%TYPE,
        P_PRECIO   IN PRODUCTO.PRECIO%TYPE,
        P_STOCK    IN PRODUCTO.STOCK%TYPE
    );

    PROCEDURE SP_ACTUALIZAR_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_PRECIO      IN PRODUCTO.PRECIO%TYPE,
        P_STOCK       IN PRODUCTO.STOCK%TYPE
    );

    PROCEDURE SP_ELIMINAR_LOGICO_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE
    );

    PROCEDURE SP_OBTENER_PRODUCTO_ID (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_RESULTADO   OUT SYS_REFCURSOR
    );

    PROCEDURE SP_LISTAR_PRODUCTOS (
        P_MARCA  IN PRODUCTO.MARCA%TYPE DEFAULT NULL,
        P_MODELO IN PRODUCTO.MODELO%TYPE DEFAULT NULL,
        P_RESULTADO OUT SYS_REFCURSOR
    );

END PKG_PRODUCTO;
/
CREATE OR REPLACE PACKAGE BODY PKG_PRODUCTO AS

    PROCEDURE SP_CREAR_PRODUCTO (
        P_CODIGO   IN PRODUCTO.CODIGO%TYPE,
        P_NOMBRE   IN PRODUCTO.NOMBRE%TYPE,
        P_MARCA    IN PRODUCTO.MARCA%TYPE,
        P_MODELO   IN PRODUCTO.MODELO%TYPE,
        P_PRECIO   IN PRODUCTO.PRECIO%TYPE,
        P_STOCK    IN PRODUCTO.STOCK%TYPE
    ) IS
    BEGIN
        INSERT INTO PRODUCTO (
            ID_PRODUCTO,
            CODIGO,
            NOMBRE,
            MARCA,
            MODELO,
            PRECIO,
            STOCK
        ) VALUES (
            SEQ_PRODUCTO.NEXTVAL,
            P_CODIGO,
            P_NOMBRE,
            P_MARCA,
            P_MODELO,
            P_PRECIO,
            P_STOCK
        );
    END SP_CREAR_PRODUCTO;


    PROCEDURE SP_ACTUALIZAR_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_PRECIO      IN PRODUCTO.PRECIO%TYPE,
        P_STOCK       IN PRODUCTO.STOCK%TYPE
    ) IS
    BEGIN
        UPDATE PRODUCTO
        SET PRECIO = P_PRECIO,
            STOCK = P_STOCK,
            FECHA_MODIF = SYSTIMESTAMP
        WHERE ID_PRODUCTO = P_ID_PRODUCTO
          AND ESTADO = 'A';
    END SP_ACTUALIZAR_PRODUCTO;


    PROCEDURE SP_ELIMINAR_LOGICO_PRODUCTO (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE
    ) IS
    BEGIN
        UPDATE PRODUCTO
        SET ESTADO = 'I',
            FECHA_MODIF = SYSTIMESTAMP
        WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    END SP_ELIMINAR_LOGICO_PRODUCTO;


    PROCEDURE SP_OBTENER_PRODUCTO_ID (
        P_ID_PRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE,
        P_RESULTADO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
        SELECT *
        FROM PRODUCTO
        WHERE ID_PRODUCTO = P_ID_PRODUCTO
          AND ESTADO = 'A';
    END SP_OBTENER_PRODUCTO_ID;


    PROCEDURE SP_LISTAR_PRODUCTOS (
        P_MARCA  IN PRODUCTO.MARCA%TYPE DEFAULT NULL,
        P_MODELO IN PRODUCTO.MODELO%TYPE DEFAULT NULL,
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
        SELECT *
        FROM PRODUCTO
        WHERE ESTADO = 'A'
          AND (P_MARCA IS NULL OR MARCA = P_MARCA)
          AND (P_MODELO IS NULL OR MODELO = P_MODELO);
    END SP_LISTAR_PRODUCTOS;

END PKG_PRODUCTO;
/
ALTER SESSION SET CONTAINER = XEPDB1;

SELECT USER FROM DUAL;

VAR RC REFCURSOR;

BEGIN
    PKG_PRODUCTO.SP_LISTAR_PRODUCTOS(NULL, NULL, :RC);
END;
/

PRINT RC;

VAR RC REFCURSOR;
BEGIN
    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRDs020', 'Laptop', 'Dell', 'Inspiron 15', 2800, 10);
    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s21', 'Laptop', 'HP', 'Pavilion 14', 2600, 8);
    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s22', 'Laptop', 'Lenovo', 'ThinkPad E14', 3200, 5);

    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s23', 'Monitor', 'Samsung', 'S24F350', 750, 15);
    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s24', 'Monitor', 'LG', '24MK430', 720, 12);

    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s25', 'Teclado', 'Logitech', 'K120', 55, 30);
    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s26', 'Mouse', 'Logitech', 'M185', 45, 40);

    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s27', 'Impresora', 'HP', 'DeskJet 2775', 480, 6);
    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s28', 'Impresora', 'Epson', 'L3250', 850, 4);

    PKG_PRODUCTO.SP_CREAR_PRODUCTO('PRD0s29', 'Disco Duro', 'Seagate', 'Barracuda 1TB', 280, 20);
END;
/
PRINT RC;
COMMIT;
SELECT * FROM PRODUCTO WHERE ESTADO = 'I';
SELECT * FROM PRODUCTO;
 


